language: python

env:
  - TOXENV=py27
  - TOXENV=py33
  - TOXENV=py34
  - TOXENV=py35
  - TOXENV=pypy
  - TOXENV=pypy3

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOXENV
